name: claimguardian-scraper
region: nyc
services:
  - name: property-scraper
    github:
      repo: your-github-username/ClaimGuardian
      branch: main
      deploy_on_push: true
    source_dir: scraper
    build_command: npm install
    run_command: npm start
    envs:
      - key: SUPABASE_URL
        scope: RUN_TIME
        value: ${SUPABASE_URL}
      - key: SUPABASE_SERVICE_ROLE_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${SUPABASE_SERVICE_ROLE_KEY}
      - key: BATCH_SIZE
        scope: RUN_TIME
        value: "500"
      - key: MAX_RETRIES
        scope: RUN_TIME
        value: "3"
      - key: RETRY_DELAY
        scope: RUN_TIME
        value: "5000"
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3