# Grafana Datasources Configuration
# ClaimGuardian AI-Powered Insurance Platform

apiVersion: 1

# List of datasources to insert/update
datasources:
  # Prometheus datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true
    jsonData:
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 15s
    secureJsonData: {}

  # Loki datasource for logs
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    version: 1
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: prometheus-uid
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
    secureJsonData: {}

  # AlertManager datasource
  - name: AlertManager
    type: alertmanager
    access: proxy
    orgId: 1
    url: http://alertmanager:9093
    version: 1
    editable: true
    jsonData:
      implementation: prometheus
    secureJsonData: {}

  # TestData datasource for development
  - name: TestData
    type: testdata
    access: proxy
    orgId: 1
    version: 1
    editable: true
    isDefault: false