#!/bin/bash

echo "🔧 Fixing user_tracking table and functions..."
echo ""
echo "This script will:"
echo "1. Add missing 'event_type' column to user_tracking table"
echo "2. Add missing 'event_data' column for storing event metadata"
echo "3. Add other missing columns (device_fingerprint, page_url, etc.)"
echo "4. Update tracking functions to work with current schema"
echo "5. Create proper indexes for performance"
echo ""
echo "Please run this SQL in your Supabase SQL Editor:"
echo "================================================"
echo ""
cat ./scripts/fix-user-tracking-table.sql
echo ""
echo "================================================"
echo ""
echo "Or use the Supabase Dashboard:"
echo "1. Go to https://supabase.com/dashboard/project/tmlrvecuwgppbaynesji/sql/new"
echo "2. Copy and paste the SQL above"
echo "3. Click 'Run'"
echo ""
echo "This fix addresses the 'column event_type does not exist' error."