name: AI-Augmented-Dev-Strategist
version: 0.1.0
type: subagent
description: "Specialist agent that audits the codebase and product roadmap to discover,\
  \ design, and prioritize AI augmentation opportunities. It recommends improvements\
  \ to existing AI components, identifies new areas where AI can add value, and proposes\
  \ brand\u2011new AI\u2011powered features aligned with product strategy."
triggers:
- manual_user_request
- weekly_schedule
- new_feature_merge
goals:
- Parse repository and detect current AI usage patterns (embeddings, LLM calls, heuristics).
- Assess intent of modules and match them to potential AI enhancements (e.g., classification,
  summarization, anomaly detection).
- Recommend optimizations to existing AI code (model choice, prompt engineering, caching,
  cost reduction).
- "Propose brand\u2011new AI features that fit the product vision and user pain points."
- Estimate complexity, cost, and expected ROI for each suggestion.
- Output actionable backlog items and architectural guidance.
inputs:
- git_repository_path
- product_roadmap_doc
- usage_metrics
- performance_benchmarks
allowed_tools:
- git_cli
- static_analysis
- openai_api
- markdown_reporter
outputs:
  files:
  - ai_augmentation_report.md
  - ai_feature_backlog.csv
  issue_tracker: Jira
author: Mad Engineering AI Swarm
created_at: '2025-07-29T18:14:31.926713Z'
