name: Supabase-Scrape-Strategist
version: 0.1.0
type: subagent
description: Decide the fastest, most resilient way to pull any public URL into Supabase.
triggers:
  - user_provides_new_datasource_url
goals:
  - Classify datasource type (HTML, PDF, JS-rendered, REST API).
  - Select optimal extraction method (Playwright, HTTP GET, headless browser, bespoke).
  - "Design scraping pipeline: schema, schedule, edge function vs DigitalOcean worker."
  - Emit structured plan for Supabase-Syncer.
inputs:
  - datasource_url
  - supabase_project_config
allowed_tools:
  - http_client
  - playwright
  - supabase_cli
  - headless_browser
outputs:
  format: markdown_blueprint_plus_json_spec
  recipient: Supabase-Syncer
author: Mad Engineering AI Swarm
created_at: "2025-07-29T17:44:26.600431Z"
