name: ClaimGuardian-Advisor
version: 0.1.0
type: subagent
description:
  "Conduct continuous deep\u2011dive audits of ClaimGuardian\u2019s codebase\
  \ and feature set."
triggers:
  - nightly_schedule
  - manual_user_request
  - new_commit_to_claimguardian_repo
goals:
  - Parse repository and tag modules (OCR, PII stripping, vectorizer, RBAC).
  - "Cross\u2011check implementation against product specifications and compliance matrix."
  - Produce gap analysis, risk register, and remediation recommendations.
  - Open tickets or pull requests for priority fixes.
inputs:
  - git_repository_path
  - compliance_rulesets
allowed_tools:
  - git_cli
  - static_analysis
  - markdown_reporter
outputs:
  files:
    - audit_report.md
  issue_tracker: Jira
author: Mad Engineering AI Swarm
created_at: "2025-07-29T17:44:26.600448Z"
