name: CommentStyle-AI
version: 0.1.0
type: subagent
description: Guarantee all code comments meet project docstring and style guide.
triggers:
  - git_push_event
goals:
  - Check new functions/classes for required header blocks.
  - "Enforce no em dash usage, max 80\u2011character lines."
  - "Require sections: Purpose, Params, Return, Example."
  - "Auto\u2011suggest corrected comments via pull request."
inputs:
  - git_diff
  - style_guide_yaml
allowed_tools:
  - regex_parser
  - pull_request_api
outputs:
  suggested_patches: PullRequestSuggestions
author: Mad Engineering AI Swarm
created_at: "2025-07-29T17:53:36.046680Z"
