name: Update Database Types

on:
  push:
    paths:
      - "supabase/migrations/*.sql"
      - "supabase/schema.sql"
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # Weekly on Monday

jobs:
  update-types:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: pnpm/action-setup@v4
        with:
          version: 10.13.1

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Generate types from production
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_PROJECT_ID: tmlrvecuwgppbaynesji
        run: |
          cd apps/web
          supabase link --project-ref $SUPABASE_PROJECT_ID
          pnpm db:types

      - name: Check for changes
        id: check-changes
        run: |
          if git diff --quiet packages/db/src/types/database.types.ts; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check-changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update database types"
          title: "chore: update database types"
          body: |
            This PR updates the TypeScript types to match the current database schema.

            Generated by the database-types workflow.
          branch: update-database-types
          delete-branch: true
